

spring:
  kafka:
    consumer:
      bootstrap-servers: kafka.default.svc.cluster.local:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: kafka.default.svc.cluster.local:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


# PushGateway
management:
  metrics:
    export:
      prometheus:
        pushgateway:
          enabled: true
          base-url: http://${PUSH_GATEWAY:prometheus-pushgateway.default.svc.cluster.local}:9091
          shutdown-operation: push
  endpoints:
    web:
      exposure:
        include: "*"