

spring:
  kafka:
    consumer:
      bootstrap-servers: kafka.default.svc.cluster.local:9092
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: kafka.default.svc.cluster.local:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.topic: ${KAFKA_TOPIC:beststories}
spring.kafka.topic.groupId: ${KAFKA_GROUPID:cg-beststories}

management:
  endpoints:
    web:
      exposure:
        include: "*"
